version: "3"
services:
  generate_pb_go:
    image: gen-go
    build:
      context: ../
      target: protoc_gen_go
      dockerfile: ./development/proto.Dockerfile
    volumes:
      - "../:/app/"
    entrypoint: /app/development/gen-proto.sh
