version: "3"
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    command: [ "redis-server", "--requirepass", "redis_pass" ]
    volumes:
      - ./redis-data:/data

  scylla:
    image: scylladb/scylla:6.0
    # restart: always
    command: --smp 1 --memory 750M --overprovisioned 1
    ports:
      - 9042:9042
      - 9100:9100 # Node Exporter
      - 9180:9180 # Scylla Metrics

  opensearch:
    image: opensearchproject/opensearch:latest
    restart: always
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=D@tabase123a
    ports:
      - 9200:9200
      - 9600:9600
