// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: msqueue/message.proto

package msqueue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "openmyth/messgener/pb/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// consumer at backend/main
type EventJson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventJson) Reset() {
	*x = EventJson{}
	mi := &file_msqueue_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventJson) ProtoMessage() {}

func (x *EventJson) ProtoReflect() protoreflect.Message {
	mi := &file_msqueue_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventJson.ProtoReflect.Descriptor instead.
func (*EventJson) Descriptor() ([]byte, []int) {
	return file_msqueue_message_proto_rawDescGZIP(), []int{0}
}

func (x *EventJson) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EventJson) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventJson) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EventJson) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// consumer at backend/main
type EventProtobuf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProtobuf) Reset() {
	*x = EventProtobuf{}
	mi := &file_msqueue_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProtobuf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProtobuf) ProtoMessage() {}

func (x *EventProtobuf) ProtoReflect() protoreflect.Message {
	mi := &file_msqueue_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProtobuf.ProtoReflect.Descriptor instead.
func (*EventProtobuf) Descriptor() ([]byte, []int) {
	return file_msqueue_message_proto_rawDescGZIP(), []int{1}
}

func (x *EventProtobuf) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EventProtobuf) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventProtobuf) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EventProtobuf) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_msqueue_message_proto protoreflect.FileDescriptor

const file_msqueue_message_proto_rawDesc = "" +
	"\n" +
	"\x15msqueue/message.proto\x12\amsqueue\x1a\x11base/option.proto\x1a\x0fbase/type.proto\"u\n" +
	"\tEventJson\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind:\x1c\x8a\x98\xe6\x05\x17\n" +
	"\x15TEST_EVENT_JSON_TOPIC\"\x7f\n" +
	"\rEventProtobuf\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind:\"\x8a\x98\xe6\x05\x1d\n" +
	"\x19TEST_EVENT_PROTOBUF_TOPIC\x10\x01B\x1fZ\x1dopenmyth/messgener/pb/msqueueb\x06proto3"

var (
	file_msqueue_message_proto_rawDescOnce sync.Once
	file_msqueue_message_proto_rawDescData []byte
)

func file_msqueue_message_proto_rawDescGZIP() []byte {
	file_msqueue_message_proto_rawDescOnce.Do(func() {
		file_msqueue_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msqueue_message_proto_rawDesc), len(file_msqueue_message_proto_rawDesc)))
	})
	return file_msqueue_message_proto_rawDescData
}

var file_msqueue_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msqueue_message_proto_goTypes = []any{
	(*EventJson)(nil),     // 0: msqueue.EventJson
	(*EventProtobuf)(nil), // 1: msqueue.EventProtobuf
}
var file_msqueue_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msqueue_message_proto_init() }
func file_msqueue_message_proto_init() {
	if File_msqueue_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msqueue_message_proto_rawDesc), len(file_msqueue_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msqueue_message_proto_goTypes,
		DependencyIndexes: file_msqueue_message_proto_depIdxs,
		MessageInfos:      file_msqueue_message_proto_msgTypes,
	}.Build()
	File_msqueue_message_proto = out.File
	file_msqueue_message_proto_goTypes = nil
	file_msqueue_message_proto_depIdxs = nil
}
