// Code generated by protoc-gen-api-info. DO NOT EDIT.
// version: 3.14.0
// source: user/auth.proto

package user

const (
	AuthService_Login_API          = "POST /v1/auth/login"
	AuthService_ForgotPassword_API = "POST /v1/auth/forgot-password"
	AuthService_Disable2FA_API     = "POST /v1/auth/otp/disable"
	AuthService_GenerateOTP_API    = "POST /v1/auth/otp/generate"
	AuthService_VerifyOTP_API      = "POST /v1/auth/otp/verify"
	AuthService_ResetPassword_API  = "POST /v1/auth/reset-password"
	AuthService_ChangePassword_API = "PUT /v1/auth/change-password"
	AuthService_Enable2FA_API      = "POST /v1/auth/otp/enable"
)

var AuthService_APIs = []string{
	AuthService_Login_API,
	AuthService_ForgotPassword_API,
	AuthService_Disable2FA_API,
	AuthService_GenerateOTP_API,
	AuthService_VerifyOTP_API,
	AuthService_ResetPassword_API,
	AuthService_ChangePassword_API,
	AuthService_Enable2FA_API,
}
