user:
  postgres:
    schema: postgres
    host: localhost
    port: "5432"
    user: user
    password: password
    database: messenger
    max_connection: 10

  endpoint:
    host: localhost
    port: "50051"

chat:
  opensearch:
    host: localhost
    port: "9200"
    user: opensearch_user
    password: opensearch_pass
    database: chat_index
    max_connection: 5

  scylla:
    schema: scylla
    host: localhost
    port: "9042"
    user: scylla_user
    password: scylla_pass
    database: chat_keyspace
    max_connection: 8

  redis:
    schema: redis
    host: localhost
    port: "6380"
    user: redis_user
    password: redis_pass
    database: chat_db
    max_connection: 8

  postgres:
    schema: postgres
    host: localhost
    port: "5432"
    user: user
    password: password
    database: messenger
    max_connection: 8

  courier:
    host: localhost
    port: "3306"
    user: courier_user
    password: courier_pass
    database: courier_db
    max_connection: 6

  endpoint:
    host: localhost
    port: "50052"

gateway:
  endpoint:
    host: localhost
    port: "8080"

security:
  symetric_key: myverysecurekey1234567890

log:
  file_output: ./logs/app.log