// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.14.0
// source: base/option.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic      string          `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	EncodeType EventEncodeType `protobuf:"varint,2,opt,name=encode_type,json=encodeType,proto3,enum=base.EventEncodeType" json:"encode_type,omitempty"` // default to json
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_base_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_base_option_proto_rawDescGZIP(), []int{0}
}

func (x *EventOptions) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventOptions) GetEncodeType() EventEncodeType {
	if x != nil {
		return x.EncodeType
	}
	return EventEncodeType_EventEncodeType_JSON
}

var file_base_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         1520001,
		Name:          "base.event",
		Tag:           "bytes,1520001,opt,name=event",
		Filename:      "base/option.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional base.EventOptions event = 1520001;
	E_Event = &file_base_option_proto_extTypes[0] // ConsumerOptions consumer = 1520002;
)

var File_base_option_proto protoreflect.FileDescriptor

var file_base_option_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x62, 0x61, 0x73,
	0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x0c,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x36, 0x0a, 0x0b, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x4b, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x81, 0xe3, 0x5c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x1c, 0x5a, 0x1a, 0x6f, 0x70, 0x65, 0x6e, 0x6d,
	0x79, 0x74, 0x68, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_base_option_proto_rawDescOnce sync.Once
	file_base_option_proto_rawDescData = file_base_option_proto_rawDesc
)

func file_base_option_proto_rawDescGZIP() []byte {
	file_base_option_proto_rawDescOnce.Do(func() {
		file_base_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_option_proto_rawDescData)
	})
	return file_base_option_proto_rawDescData
}

var file_base_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_option_proto_goTypes = []any{
	(*EventOptions)(nil),                // 0: base.EventOptions
	(EventEncodeType)(0),                // 1: base.EventEncodeType
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_base_option_proto_depIdxs = []int32{
	1, // 0: base.EventOptions.encode_type:type_name -> base.EventEncodeType
	2, // 1: base.event:extendee -> google.protobuf.MessageOptions
	0, // 2: base.event:type_name -> base.EventOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_option_proto_init() }
func file_base_option_proto_init() {
	if File_base_option_proto != nil {
		return
	}
	file_base_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_base_option_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EventOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_option_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_base_option_proto_goTypes,
		DependencyIndexes: file_base_option_proto_depIdxs,
		MessageInfos:      file_base_option_proto_msgTypes,
		ExtensionInfos:    file_base_option_proto_extTypes,
	}.Build()
	File_base_option_proto = out.File
	file_base_option_proto_rawDesc = nil
	file_base_option_proto_goTypes = nil
	file_base_option_proto_depIdxs = nil
}
