// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: base/option.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	EncodeType    EventEncodeType        `protobuf:"varint,2,opt,name=encode_type,json=encodeType,proto3,enum=base.EventEncodeType" json:"encode_type,omitempty"` // default to json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventOptions) Reset() {
	*x = EventOptions{}
	mi := &file_base_option_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventOptions) ProtoMessage() {}

func (x *EventOptions) ProtoReflect() protoreflect.Message {
	mi := &file_base_option_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventOptions.ProtoReflect.Descriptor instead.
func (*EventOptions) Descriptor() ([]byte, []int) {
	return file_base_option_proto_rawDescGZIP(), []int{0}
}

func (x *EventOptions) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventOptions) GetEncodeType() EventEncodeType {
	if x != nil {
		return x.EncodeType
	}
	return EventEncodeType_EventEncodeType_JSON
}

var file_base_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*EventOptions)(nil),
		Field:         1520001,
		Name:          "base.event",
		Tag:           "bytes,1520001,opt,name=event",
		Filename:      "base/option.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional base.EventOptions event = 1520001;
	E_Event = &file_base_option_proto_extTypes[0] // ConsumerOptions consumer = 1520002;
)

var File_base_option_proto protoreflect.FileDescriptor

const file_base_option_proto_rawDesc = "" +
	"\n" +
	"\x11base/option.proto\x12\x04base\x1a google/protobuf/descriptor.proto\x1a\x0fbase/type.proto\"\\\n" +
	"\fEventOptions\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x126\n" +
	"\vencode_type\x18\x02 \x01(\x0e2\x15.base.EventEncodeTypeR\n" +
	"encodeType:K\n" +
	"\x05event\x12\x1f.google.protobuf.MessageOptions\x18\x81\xe3\\ \x01(\v2\x12.base.EventOptionsR\x05eventB\x1cZ\x1aopenmyth/messgener/pb/baseb\x06proto3"

var (
	file_base_option_proto_rawDescOnce sync.Once
	file_base_option_proto_rawDescData []byte
)

func file_base_option_proto_rawDescGZIP() []byte {
	file_base_option_proto_rawDescOnce.Do(func() {
		file_base_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_option_proto_rawDesc), len(file_base_option_proto_rawDesc)))
	})
	return file_base_option_proto_rawDescData
}

var file_base_option_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_option_proto_goTypes = []any{
	(*EventOptions)(nil),                // 0: base.EventOptions
	(EventEncodeType)(0),                // 1: base.EventEncodeType
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_base_option_proto_depIdxs = []int32{
	1, // 0: base.EventOptions.encode_type:type_name -> base.EventEncodeType
	2, // 1: base.event:extendee -> google.protobuf.MessageOptions
	0, // 2: base.event:type_name -> base.EventOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_option_proto_init() }
func file_base_option_proto_init() {
	if File_base_option_proto != nil {
		return
	}
	file_base_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_option_proto_rawDesc), len(file_base_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_base_option_proto_goTypes,
		DependencyIndexes: file_base_option_proto_depIdxs,
		MessageInfos:      file_base_option_proto_msgTypes,
		ExtensionInfos:    file_base_option_proto_extTypes,
	}.Build()
	File_base_option_proto = out.File
	file_base_option_proto_goTypes = nil
	file_base_option_proto_depIdxs = nil
}
