// Code generated by protoc-gen-enum. DO NOT EDIT.
// version: 3.14.0
// source: base/type.proto

package base

import "fmt"

func (x EventEncodeType) FromString(str string) (EventEncodeType, error) {
	switch str {
	case EventEncodeType_EventEncodeType_JSON.String():
		return EventEncodeType_EventEncodeType_JSON, nil
	case EventEncodeType_EventEncodeType_Protobuf.String():
		return EventEncodeType_EventEncodeType_Protobuf, nil
	default:
		return EventEncodeType(0), fmt.Errorf("unknown %s", str)
	}
}
