// Code generated by protoc-gen-api-info. DO NOT EDIT.
// version: 3.14.0
// source: chat/channel.proto

package chat

const (
	ChannelService_SearchChannelByName_API = "POST /v1/channels"
)

var ChannelService_APIs = []string{
	ChannelService_SearchChannelByName_API,
}
