// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: chat/channel.proto

package chat

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_chat_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_chat_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_chat_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SearchChannelByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChannelByNameRequest) Reset() {
	*x = SearchChannelByNameRequest{}
	mi := &file_chat_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChannelByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChannelByNameRequest) ProtoMessage() {}

func (x *SearchChannelByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChannelByNameRequest.ProtoReflect.Descriptor instead.
func (*SearchChannelByNameRequest) Descriptor() ([]byte, []int) {
	return file_chat_channel_proto_rawDescGZIP(), []int{1}
}

func (x *SearchChannelByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchChannelByNameRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchChannelByNameRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchChannelByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChannelByNameResponse) Reset() {
	*x = SearchChannelByNameResponse{}
	mi := &file_chat_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChannelByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChannelByNameResponse) ProtoMessage() {}

func (x *SearchChannelByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChannelByNameResponse.ProtoReflect.Descriptor instead.
func (*SearchChannelByNameResponse) Descriptor() ([]byte, []int) {
	return file_chat_channel_proto_rawDescGZIP(), []int{2}
}

func (x *SearchChannelByNameResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type GetListChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListChannelRequest) Reset() {
	*x = GetListChannelRequest{}
	mi := &file_chat_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListChannelRequest) ProtoMessage() {}

func (x *GetListChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListChannelRequest.ProtoReflect.Descriptor instead.
func (*GetListChannelRequest) Descriptor() ([]byte, []int) {
	return file_chat_channel_proto_rawDescGZIP(), []int{3}
}

func (x *GetListChannelRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListChannelRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListChannelResponse) Reset() {
	*x = GetListChannelResponse{}
	mi := &file_chat_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListChannelResponse) ProtoMessage() {}

func (x *GetListChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListChannelResponse.ProtoReflect.Descriptor instead.
func (*GetListChannelResponse) Descriptor() ([]byte, []int) {
	return file_chat_channel_proto_rawDescGZIP(), []int{4}
}

func (x *GetListChannelResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_chat_channel_proto protoreflect.FileDescriptor

const file_chat_channel_proto_rawDesc = "" +
	"\n" +
	"\x12chat/channel.proto\x12\x04chat\x1a\x1cgoogle/api/annotations.proto\"^\n" +
	"\aChannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"^\n" +
	"\x1aSearchChannelByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"H\n" +
	"\x1bSearchChannelByNameResponse\x12)\n" +
	"\bchannels\x18\x01 \x03(\v2\r.chat.ChannelR\bchannels\"E\n" +
	"\x15GetListChannelRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"C\n" +
	"\x16GetListChannelResponse\x12)\n" +
	"\bchannels\x18\x01 \x03(\v2\r.chat.ChannelR\bchannels2\xec\x01\n" +
	"\x0eChannelService\x12w\n" +
	"\x13SearchChannelByName\x12 .chat.SearchChannelByNameRequest\x1a!.chat.SearchChannelByNameResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/channels/search\x12a\n" +
	"\x0eGetListChannel\x12\x1b.chat.GetListChannelRequest\x1a\x1c.chat.GetListChannelResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/channelsB\x1cZ\x1aopenmyth/messgener/pb/chatb\x06proto3"

var (
	file_chat_channel_proto_rawDescOnce sync.Once
	file_chat_channel_proto_rawDescData []byte
)

func file_chat_channel_proto_rawDescGZIP() []byte {
	file_chat_channel_proto_rawDescOnce.Do(func() {
		file_chat_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_channel_proto_rawDesc), len(file_chat_channel_proto_rawDesc)))
	})
	return file_chat_channel_proto_rawDescData
}

var file_chat_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chat_channel_proto_goTypes = []any{
	(*Channel)(nil),                     // 0: chat.Channel
	(*SearchChannelByNameRequest)(nil),  // 1: chat.SearchChannelByNameRequest
	(*SearchChannelByNameResponse)(nil), // 2: chat.SearchChannelByNameResponse
	(*GetListChannelRequest)(nil),       // 3: chat.GetListChannelRequest
	(*GetListChannelResponse)(nil),      // 4: chat.GetListChannelResponse
}
var file_chat_channel_proto_depIdxs = []int32{
	0, // 0: chat.SearchChannelByNameResponse.channels:type_name -> chat.Channel
	0, // 1: chat.GetListChannelResponse.channels:type_name -> chat.Channel
	1, // 2: chat.ChannelService.SearchChannelByName:input_type -> chat.SearchChannelByNameRequest
	3, // 3: chat.ChannelService.GetListChannel:input_type -> chat.GetListChannelRequest
	2, // 4: chat.ChannelService.SearchChannelByName:output_type -> chat.SearchChannelByNameResponse
	4, // 5: chat.ChannelService.GetListChannel:output_type -> chat.GetListChannelResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_chat_channel_proto_init() }
func file_chat_channel_proto_init() {
	if File_chat_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_channel_proto_rawDesc), len(file_chat_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_channel_proto_goTypes,
		DependencyIndexes: file_chat_channel_proto_depIdxs,
		MessageInfos:      file_chat_channel_proto_msgTypes,
	}.Build()
	File_chat_channel_proto = out.File
	file_chat_channel_proto_goTypes = nil
	file_chat_channel_proto_depIdxs = nil
}
