// Code generated by protoc-gen-api-info. DO NOT EDIT.
// version: 3.14.0
// source: chat/message.proto

package chat

const (
	MessageService_GetMessageListChannel_API = "POST /v1/channels/*/messages"
)

var MessageService_APIs = []string{
	MessageService_GetMessageListChannel_API,
}
