// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: msqueue/message.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EventJson with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventJson) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventJson with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventJsonMultiError, or nil
// if none found.
func (m *EventJson) ValidateAll() error {
	return m.validate(true)
}

func (m *EventJson) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for To

	// no validation rules for Type

	// no validation rules for Code

	// no validation rules for Kind

	if len(errors) > 0 {
		return EventJsonMultiError(errors)
	}

	return nil
}

// EventJsonMultiError is an error wrapping multiple validation errors returned
// by EventJson.ValidateAll() if the designated constraints aren't met.
type EventJsonMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventJsonMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventJsonMultiError) AllErrors() []error { return m }

// EventJsonValidationError is the validation error returned by
// EventJson.Validate if the designated constraints aren't met.
type EventJsonValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventJsonValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventJsonValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventJsonValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventJsonValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventJsonValidationError) ErrorName() string { return "EventJsonValidationError" }

// Error satisfies the builtin error interface
func (e EventJsonValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventJson.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventJsonValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventJsonValidationError{}

// Validate checks the field values on EventProtobuf with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventProtobuf) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventProtobuf with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventProtobufMultiError, or
// nil if none found.
func (m *EventProtobuf) ValidateAll() error {
	return m.validate(true)
}

func (m *EventProtobuf) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for To

	// no validation rules for Type

	// no validation rules for Code

	// no validation rules for Kind

	if len(errors) > 0 {
		return EventProtobufMultiError(errors)
	}

	return nil
}

// EventProtobufMultiError is an error wrapping multiple validation errors
// returned by EventProtobuf.ValidateAll() if the designated constraints
// aren't met.
type EventProtobufMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventProtobufMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventProtobufMultiError) AllErrors() []error { return m }

// EventProtobufValidationError is the validation error returned by
// EventProtobuf.Validate if the designated constraints aren't met.
type EventProtobufValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventProtobufValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventProtobufValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventProtobufValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventProtobufValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventProtobufValidationError) ErrorName() string { return "EventProtobufValidationError" }

// Error satisfies the builtin error interface
func (e EventProtobufValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventProtobuf.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventProtobufValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventProtobufValidationError{}
