// Code generated by protoc-gen-event. DO NOT EDIT.
// version: 3.14.0
// source: msqueue/message.proto

package pb

import (
	"encoding/json"
	proto "google.golang.org/protobuf/proto"
)

const TEST_EVENT_JSON_TOPIC = "TEST_EVENT_JSON_TOPIC" // event

// Marshal marshals a EventJson to bytes
func (x *EventJson) Marshal() ([]byte, error) {
	b, err := json.Marshal(x)
	if err != nil {
		return nil, err
	}
	return b, nil
}

// Unmarshal unmarshals from bytes to a EventJson
func (x EventJson) Unmarshal(b []byte) error {
	if err := json.Unmarshal(b, &x); err != nil {
		return err
	}
	return nil
}

const TEST_EVENT_PROTOBUF_TOPIC = "TEST_EVENT_PROTOBUF_TOPIC" // event

// Marshal marshals a EventProtobuf to bytes
func (x *EventProtobuf) Marshal() ([]byte, error) {
	b, err := proto.Marshal(x)
	if err != nil {
		return nil, err
	}
	return b, nil
}

// Unmarshal unmarshals from bytes to a EventProtobuf
func (x EventProtobuf) Unmarshal(b []byte) error {
	if err := proto.Unmarshal(b, &x); err != nil {
		return err
	}
	return nil
}
